Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2022-09, with the labels that each got.

#19 New release - Contains merge from IDE-CE
  .npmrc
  .storybook/main.js
  .storybook/middleware.js
  .storybook/preview.js
  CHANGELOG.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  scripts/deployApp.sh
  scripts/detach_manifest.py
  scripts/import_callback.sh
  src/editors/Callback/view/Callback.jsx
  src/editors/Flow/view/Components/Links/BaseLink.js
  src/editors/Flow/view/Components/Nodes/BaseNode/BaseNode.js
  src/editors/Flow/view/Components/Nodes/BaseNode/TreeView/TreeNode.js
  src/editors/Flow/view/Components/interface/InterfaceModes.js
  src/editors/Flow/view/Components/interface/canvas.js
  src/editors/Flow/view/Core/Graph/GraphTreeView.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/events.js
  src/plugins/views/Explorer/Explorer.jsx
  src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
  src/plugins/views/MainMenu/MainMenu.jsx
  src/plugins/views/SystemBar/builder/buildSubMenus.js
  src/stories/AppCE.jsx
  src/stories/AppCE.stories.jsx
  src/stories/_mockLogin.js
  src/tools/HomeTab/components/QuickAccess.jsx
Labels: release candidate

#21 New Release
  CHANGELOG.md
  database/Callback/backend.DataValidation.py
  jest.config.js
  package-lock.json
  package.json
  src/__mocks__/@mov-ai/mov-fe-lib-core.js
  src/__mocks__/@mov-ai/mov-fe-lib-react.js
  src/__mocks__/fileMock.js
  src/editors/_shared/ConfigurationSelector/ConfigurationSelector.jsx
  src/editors/_shared/KeyValueTable/ParametersEditorDialog.jsx
  src/editors/_shared/hooks/DataTypes/types/BooleanType.js
  src/editors/_shared/hooks/DataTypes/types/BooleanType.test.js
  src/editors/_shared/hooks/DataTypes/types/ConfigurationType.js
  src/editors/_shared/hooks/useDataTypes.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/stories/components/ConfigurationSelector.stories.jsx
  src/utils/Constants.js
Labels: release candidate

#22 Data types validation: Boolean default value
  src/editors/_shared/KeyValueTable/ParametersEditorDialog.jsx
  src/editors/_shared/hooks/DataTypes/AbstractDataType.js
  src/editors/_shared/hooks/DataTypes/types/BooleanType.js
  src/editors/_shared/hooks/useDataTypes.js
  src/stories/AppCE.jsx
  src/stories/components/DataTypes.stories.jsx
Labels: bug

#23 New Release
  src/editors/_shared/KeyValueTable/ParametersEditorDialog.jsx
  src/editors/_shared/hooks/DataTypes/AbstractDataType.js
  src/editors/_shared/hooks/DataTypes/types/BooleanType.js
  src/editors/_shared/hooks/useDataTypes.js
  src/stories/AppCE.jsx
  src/stories/components/DataTypes.stories.jsx
Labels: release candidate

#24 Fixed missing props on Form Dialog
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/ConfirmationDialog/ConfirmationDialog.jsx
  src/plugins/Dialog/components/FormDialog/NewDocumentDialog.jsx
Labels: bug

#25 Implement story to test bookmark manager
  src/App/BaseApp.js
  src/decorators/withBookmarks.jsx
  src/decorators/withMenuHandler.jsx
  src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
  src/plugins/views/MainMenu/MainMenu.jsx
  src/stories/components/Bookmarks/BookmarkManager.jsx
  src/stories/components/Bookmarks/Bookmarks.stories.jsx
  src/utils/Constants.js
Labels: bug, enhancement

#26 New release
  src/App/BaseApp.js
  src/decorators/withBookmarks.jsx
  src/decorators/withMenuHandler.jsx
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/ConfirmationDialog/ConfirmationDialog.jsx
  src/plugins/Dialog/components/FormDialog/NewDocumentDialog.jsx
  src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
  src/plugins/views/MainMenu/MainMenu.jsx
  src/stories/components/Bookmarks/BookmarkManager.jsx
  src/stories/components/Bookmarks/Bookmarks.stories.jsx
  src/utils/Constants.js
Labels: release candidate

#27 Improvements
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/engine/index.js
  src/store/Store.js
  src/stories/components/Bookmarks/BookmarkManager.jsx
  src/tools/AppShortcuts/AppShortcuts.jsx
  src/tools/AppShortcuts/Shortcuts.jsx
  src/tools/HomeTab/HomeTab.jsx
  src/utils/Utils.js
Labels: enhancement

#28 New release
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/engine/index.js
  src/store/Store.js
  src/stories/components/Bookmarks/BookmarkManager.jsx
  src/tools/AppShortcuts/AppShortcuts.jsx
  src/tools/AppShortcuts/Shortcuts.jsx
  src/tools/HomeTab/HomeTab.jsx
  src/utils/Utils.js
Labels: release candidate

#30 New release
  src/store/BaseStore.js
Labels: release candidate
