Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2022-10, with the labels that each got.

#34 FP-2032 : Added success message on doc deletion
  README.md
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/plugins/views/Explorer/Explorer.jsx
  src/stories/_mockLogin.js
  src/utils/Messages.js
Labels: enhancement

#37 FP-2074 : Fix Subflows not animating
  CHANGELOG.md
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/editors/Flow/view/Core/Graph/GraphTreeView.js
Labels: bug

#38 FP-2031 : Only 1 selections allowed on Flow Editor
  CHANGELOG.md
  src/editors/Flow/view/Flow.jsx
Labels: bug, enhancement

#35 FP-2073 : Allow to close untitled document
  CHANGELOG.md
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/store/Store.js
Labels: bug

#39 Multiple fixes on lib-ide
  index.js
  src/App/AppSettings.js
  src/decorators/index.js
  src/decorators/withKeyBinds.jsx
  src/decorators/withMenuHandler.jsx
  src/editors/Flow/view/Components/FlowTopBar/FlowSearch.jsx
  src/editors/Flow/view/Flow.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/plugins/Alerts/Alerts.js
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/AppDialog/AppDialog.jsx
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/tools/AppShortcuts/shortcuts.js
  src/utils/Constants.js
  src/utils/Utils.js
  src/utils/shortcuts.js
Labels: bug, enhancement, refactor

#40 New release
  CHANGELOG.md
  README.md
  index.js
  src/App/AppSettings.js
  src/decorators/index.js
  src/decorators/withKeyBinds.jsx
  src/decorators/withMenuHandler.jsx
  src/editors/Flow/view/Components/FlowTopBar/FlowSearch.jsx
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/editors/Flow/view/Core/Graph/GraphTreeView.js
  src/editors/Flow/view/Flow.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/plugins/Alerts/Alerts.js
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/AppDialog/AppDialog.jsx
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Explorer/Explorer.jsx
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/store/Store.js
  src/stories/_mockLogin.js
  src/tools/AppShortcuts/shortcuts.js
  src/utils/Constants.js
  src/utils/Messages.js
  src/utils/Utils.js
  src/utils/shortcuts.js
Labels: release candidate

#41 FP-2089 : Make shortcuts keybindings generic
  package-lock.json
  package.json
  src/App/AppSettings.js
  src/editors/Flow/model/Flow.js
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Components/Warnings/components/ExposedPortLine.jsx
  src/editors/Flow/view/Components/Warnings/components/ParameterLine.jsx
  src/editors/Flow/view/Views/Monitoring.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/models/Model/BaseModel.js
  src/models/subModels/Port/Port.js
  src/plugins/Dialog/Dialog.js
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/store/BaseStore.js
  src/store/Store.js
  src/stories/components/Bookmarks/BookmarkManager.jsx
  src/tools/AppShortcuts/AppShortcuts.jsx
  src/tools/AppShortcuts/Shortcuts.jsx
  src/tools/HomeTab/HomeTab.jsx
  src/utils/Constants.js
  src/utils/Utils.js
Labels: enhancement, refactor
