Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2022-12, with the labels that each got.

#58 FP-2097 : Close tab doesn't remove bookmarks when localStorage is deleted
  src/plugins/views/Tabs/hooks/useTabLayout.js
Labels: bug

#59 FP-2157 : Added validation for invalidTab to update menus
  src/decorators/withMenuHandler.jsx
Labels: bug

#62 New release
  CHANGELOG.md
  package-lock.json
  package.json
  src/decorators/withMenuHandler.jsx
  src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
  src/plugins/views/Tabs/hooks/useTabLayout.js
Labels: release candidate

#63 FP-2159 : Fixed small visual issues
  src/editors/_shared/DetailsMenu/styles.js
  src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
  src/plugins/views/Explorer/components/ListItemTree/styles.js
  src/plugins/views/MainMenu/styles.js
  src/plugins/views/SystemBar/styles.js
Labels: enhancement

#64 Fp 2152 create new editor will close editor window
  CHANGELOG.md
  src/plugins/DocManager/DocManager.js
Labels: bug

#66 FP-2096: Alternative to Paulo's solution
  src/plugins/views/Explorer/Explorer.jsx
Labels: bug, duplicate

#67 FP-2171 : Added a way to add the App Menu
  src/App/AppSettings.js
  src/App/BaseApp.js
  src/plugins/views/MainMenu/MainMenu.jsx
  src/plugins/views/MainMenu/styles.js
Labels: enhancement, refactor

#68 new release
  CHANGELOG.md
  package-lock.json
  package.json
  src/App/AppSettings.js
  src/App/BaseApp.js
  src/editors/Callback/store/CallbackStore.js
  src/editors/_shared/DetailsMenu/styles.js
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Explorer/Explorer.jsx
  src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
  src/plugins/views/Explorer/components/ListItemTree/styles.js
  src/plugins/views/MainMenu/MainMenu.jsx
  src/plugins/views/MainMenu/styles.js
  src/plugins/views/SystemBar/styles.js
Labels: release candidate
