Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2022-11, with the labels that each got.

#43 FP-2087 : Extended functionality for editors - minor refactor
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  index.js
  src/editors/Callback/index.js
  src/editors/Callback/view/Callback.jsx
  src/editors/Configuration/index.js
  src/editors/Configuration/view/Configuration.jsx
  src/editors/Flow/index.js
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Components/Menus/ContextMenu/index.js
  src/editors/Flow/view/Components/Menus/ContextMenu/modes.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/contextOptions.js
  src/editors/Node/index.js
  src/editors/Node/view/Node.jsx
  src/tools/index.js
  src/utils/Constants.js
Labels: enhancement, refactor

#45 New release
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  index.js
  package-lock.json
  package.json
  src/App/AppSettings.js
  src/editors/Callback/index.js
  src/editors/Callback/view/Callback.jsx
  src/editors/Configuration/index.js
  src/editors/Configuration/view/Configuration.jsx
  src/editors/Flow/index.js
  src/editors/Flow/model/Flow.js
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Components/Menus/ContextMenu/index.js
  src/editors/Flow/view/Components/Menus/ContextMenu/modes.js
  src/editors/Flow/view/Components/Warnings/components/ExposedPortLine.jsx
  src/editors/Flow/view/Components/Warnings/components/ParameterLine.jsx
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/Monitoring.jsx
  src/editors/Flow/view/contextOptions.js
  src/editors/Node/index.js
  src/editors/Node/view/Node.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/models/Model/BaseModel.js
  src/models/subModels/Port/Port.js
  src/plugins/Dialog/Dialog.js
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/store/BaseStore.js
  src/store/Store.js
  src/stories/components/Bookmarks/BookmarkManager.jsx
  src/tools/AppShortcuts/AppShortcuts.jsx
  src/tools/AppShortcuts/Shortcuts.jsx
  src/tools/HomeTab/HomeTab.jsx
  src/tools/index.js
  src/utils/Constants.js
  src/utils/Utils.js
Labels: enhancement, release candidate

#46 Fix keybindings in dialogs
  src/decorators/withMenuHandler.jsx
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/AppDialog/AppDialog.jsx
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/plugins/views/Tabs/hooks/useTabStack.js
  src/stories/AppCE.jsx
  src/stories/components/ConfigurationSelector.stories.jsx
  src/stories/components/PluginManager/PluginManager.stories.jsx
Labels: bug

#49 new release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release candidate

#52 FP-2126 : Fixed issues with context menu options not working
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/contextOptions.js
Labels: bug, refactor

#51 FP-2086 : Removed all references to groups and layers on Flow
  src/editors/Flow/model/Flow.js
  src/editors/Flow/model/Flow.test.js
  src/editors/Flow/model/data/flows.js
  src/editors/Flow/model/subModels/Group/Group.js
  src/editors/Flow/model/subModels/Group/Group.test.js
  src/editors/Flow/model/subModels/Group/schema.js
  src/editors/Flow/model/subModels/Layer/Layer.js
  src/editors/Flow/model/subModels/Layer/Layer.test.js
  src/editors/Flow/model/subModels/Layer/LayerManager.js
  src/editors/Flow/model/subModels/Layer/LayerManager.test.js
  src/editors/Flow/model/subModels/Layer/schema.js
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.test.js
  src/editors/Flow/model/subModels/NodeInstance/NodeInstanceManager.test.js
  src/editors/Flow/model/subModels/index.js
  src/editors/Flow/view/Components/Menus/Menu.jsx
  src/editors/Flow/view/Components/Menus/NodeMenu.jsx
  src/editors/Flow/view/Components/Menus/styles.js
  src/editors/Flow/view/Components/Menus/sub-components/GroupItem.jsx
  src/editors/Flow/view/Components/Menus/sub-components/collapsibleSections/NodeGroupSection.jsx
  src/editors/Flow/view/Components/Nodes/BaseNode/BaseNode.js
  src/editors/Flow/view/Components/Nodes/BaseNode/BaseNodeStruct.js
  src/editors/Flow/view/Components/interface/MainInterface.js
  src/editors/Flow/view/Flow.jsx
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/models/subModels/IdBasedModel/IdBasedManager.test.js
  src/models/subModels/IdBasedModel/IdBasedModel.test.js
Labels: bug, enhancement, refactor

#54 New release
  CHANGELOG.md
  package-lock.json
  src/editors/Flow/model/Flow.js
  src/editors/Flow/model/Flow.test.js
  src/editors/Flow/model/data/flows.js
  src/editors/Flow/model/subModels/Group/Group.js
  src/editors/Flow/model/subModels/Group/Group.test.js
  src/editors/Flow/model/subModels/Group/schema.js
  src/editors/Flow/model/subModels/Layer/Layer.js
  src/editors/Flow/model/subModels/Layer/Layer.test.js
  src/editors/Flow/model/subModels/Layer/LayerManager.js
  src/editors/Flow/model/subModels/Layer/LayerManager.test.js
  src/editors/Flow/model/subModels/Layer/schema.js
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.test.js
  src/editors/Flow/model/subModels/NodeInstance/NodeInstanceManager.test.js
  src/editors/Flow/model/subModels/index.js
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Components/Menus/Menu.jsx
  src/editors/Flow/view/Components/Menus/NodeMenu.jsx
  src/editors/Flow/view/Components/Menus/styles.js
  src/editors/Flow/view/Components/Menus/sub-components/GroupItem.jsx
  src/editors/Flow/view/Components/Menus/sub-components/collapsibleSections/NodeGroupSection.jsx
  src/editors/Flow/view/Components/Nodes/BaseNode/BaseNode.js
  src/editors/Flow/view/Components/Nodes/BaseNode/BaseNodeStruct.js
  src/editors/Flow/view/Components/interface/MainInterface.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/contextOptions.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/models/subModels/IdBasedModel/IdBasedManager.test.js
  src/models/subModels/IdBasedModel/IdBasedModel.test.js
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Explorer/Explorer.jsx
  src/plugins/views/Tabs/hooks/useTabLayout.js
Labels: release candidate
