Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-05, with the labels that each got.

#116 FP-2409: Added a validation to activateEditor based on the activeTab
  CHANGELOG.md
  package-lock.json
  package.json
  src/decorators/withMenuHandler.jsx
  src/editors/Flow/view/Flow.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
Labels: bug, refactor

#124 FP-2406: Make menu be able to persist on IDE
  CHANGELOG.md
  package-lock.json
  package.json
  src/App/BaseApp.js
  src/plugins/views/MainMenu/MainMenu.jsx
Labels: bug, refactor

#127 FP-2427: Update node instances when port messages change
  CHANGELOG.md
  src/editors/Node/view/components/IOConfig/IOConfig.jsx
Labels: bug

#133 New release
  CHANGELOG.md
  src/models/subModels/Parameter/Parameter.js
Labels: bug, release candidate
