Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-03, with the labels that each got.

#87 FP-2221 - Disable the Language server
  CHANGELOG.md
  src/App/BaseApp.js
  src/editors/Callback/view/Callback.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/plugins/DocManager/factory.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/stories/AppCE.jsx
Labels: bug

#89 FP-2238 - Logout behavior is different in IDE
  CHANGELOG.md
  package-lock.json
  package.json
  src/App/AppSettings.js
  src/plugins/views/MainMenu/MainMenu.jsx
Labels: bug

#90 new release
  CHANGELOG.md
  package-lock.json
  package.json
  src/App/AppSettings.js
  src/plugins/views/MainMenu/MainMenu.jsx
Labels: bug, release candidate

#92 FP-2241: Now reloading the files after saving a new file
  CHANGELOG.md
  package-lock.json
  package.json
  src/editors/Node/view/Node.jsx
  src/plugins/DocManager/DocManager.js
  src/plugins/DocManager/useDataSubscriber.js
  src/store/Store.js
Labels: bug, refactor

#93 FP-2240: Add event.preventDefault to save function to not cause the HTML save popup to open
  CHANGELOG.md
  src/plugins/DocManager/DataHandler.jsx
Labels: bug

#94 New release
  CHANGELOG.md
  package-lock.json
  package.json
  src/editors/Flow/view/contextOptions.js
  src/editors/Node/view/Node.jsx
  src/plugins/DocManager/DataHandler.jsx
  src/plugins/DocManager/DocManager.js
  src/plugins/DocManager/useDataSubscriber.js
  src/store/Store.js
Labels: bug, release candidate

#99 FP-2252: Added optional chaining to prevent breaking save
  src/store/BaseStore.js
Labels: bug
