Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-04, with the labels that each got.

#102 FP-2253: Added a fix for flow losing interface context
  src/editors/Flow/view/Core/Graph/GraphValidator.js
  src/editors/Flow/view/Flow.jsx
Labels: bug

#103 FP-2348: Added context menu to nodes in tree view
  CHANGELOG.md
  src/editors/Flow/model/Flow.js
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Components/Menus/ContextMenu/ContextMenu.jsx
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Components/Nodes/BaseNode/TreeView/TreeNode.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/contextOptions.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/utils/Messages.js
  src/utils/Utils.js
Labels: enhancement, refactor

#105 FP-2319: Removed all references to forum
  CHANGELOG.md
  src/App/AppSettings.js
  src/plugins/views/SystemBar/builder/buildMenus.js
  src/tools/HomeTab/components/QuickAccess.jsx
Labels: refactor

#104 FP-2250: Added a debounce for the robot status going offline snackbar
  CHANGELOG.md
  src/editors/Flow/view/Components/FlowTopBar/hooks/useNodeStatusUpdate.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
Labels: bug, refactor

#108 New release
  CHANGELOG.md
  src/editors/Flow/view/Components/FlowTopBar/hooks/useNodeStatusUpdate.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
Labels: release candidate

#110 new release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release candidate

#111 FP-2411: Only save params when necessary
  CHANGELOG.md
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
  src/editors/Flow/view/Components/Menus/sub-components/TableKeyValue.jsx
  src/editors/Flow/view/Components/Menus/sub-components/collapsibleSections/PropertyItem.jsx
  src/utils/Utils.js
Labels: bug, refactor

#112 new release
  CHANGELOG.md
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
  src/editors/Flow/view/Components/Menus/sub-components/TableKeyValue.jsx
  src/editors/Flow/view/Components/Menus/sub-components/collapsibleSections/PropertyItem.jsx
  src/utils/Utils.js
Labels: bug

#114 FP-2414: Fixed an issue where we were always removing the bookmarks, even when not needed
  CHANGELOG.md
  src/decorators/withMenuHandler.jsx
Labels: bug

#115 New release
  CHANGELOG.md
  src/decorators/withMenuHandler.jsx
  src/editors/Flow/view/Components/FlowBottomBar/styles.js
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Flow.jsx
Labels: bug

#119 new release
  src/decorators/withMenuHandler.jsx
Labels: bug, release candidate

#120 FP-2433: Now correctly using template defaults
  src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
Labels: bug
