Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-02, with the labels that each got.

#78 ToolReactPlugin - remove ToolComponent
  src/engine/ReactPlugin/ToolReactPlugin.js
Labels: bug

#77 FP-2218: Added a way to re-add the theme toggle if needed
  src/App/AppSettings.js
  src/decorators/withBookmarks.jsx
  src/plugins/views/MainMenu/MainMenu.jsx
  src/utils/Utils.js
Labels: bug, refactor

#79 New release
  src/App/AppSettings.js
  src/decorators/withBookmarks.jsx
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/plugins/views/MainMenu/MainMenu.jsx
  src/utils/Utils.js
Labels: release candidate

#80 New release
  package-lock.json
  package.json
Labels: enhancement, release candidate

#82 FP-2232: No longer showing own flow from add Flow menu
  src/editors/Flow/view/Components/Explorer/Explorer.jsx
  src/stories/_mockLogin.js
Labels: bug

#84 FP-2261: Added Open Callback option to Port Context Menu
  CHANGELOG.md
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/contextOptions.js
  src/utils/Utils.js
Labels: bug

#85 new release
  CHANGELOG.md
  package-lock.json
  package.json
  src/App/BaseApp.js
  src/editors/Configuration/view/Configuration.jsx
  src/editors/Flow/view/Components/Explorer/Explorer.jsx
  src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/styles.js
  src/editors/Flow/view/contextOptions.js
  src/editors/_shared/Search/styles.js
  src/plugins/hosts/DrawerPanel/styles.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/plugins/views/Tabs/styles.js
  src/store/BaseStore.js
  src/stories/AppCE.jsx
  src/stories/_mockLogin.js
  src/tools/AppShortcuts/styles.js
  src/tools/HomeTab/styles.js
  src/utils/Utils.js
  src/utils/components/Search/styles.js
Labels: bug, enhancement, release candidate
