Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-07, with the labels that each got.

#161 FP-2277: Give back focus to Flow Editor after losing focus on some cases
  CHANGELOG.md
  src/decorators/withBookmarks.jsx
  src/editors/Flow/view/Components/Debugging/DependencyInfo.jsx
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/BaseFlow.jsx
Labels: bug

#168 FP-2535: Fixed issue with deleting subflows from flow
  CHANGELOG.md
  src/editors/Flow/model/Flow.js
Labels: bug

#171 Fp 2540 duplicated code on the new merge request
  CHANGELOG.md
  src/models/subModels/Parameter/ParameterWithType.js
Labels: bug, refactor

#172 New release
  CHANGELOG.md
  src/models/subModels/Parameter/ParameterWithType.js
Labels: bug, release candidate, refactor

#173 FP-2541 - Invalid links warning message is missing in removing port
  CHANGELOG.md
  src/editors/Flow/view/Components/FlowBottomBar/FlowBottomBar.jsx
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Components/interface/MainInterface.js
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/BaseFlow.jsx
Labels: bug

#175 Revert "FP-2541 - Invalid links warning message is missing in removing port (#173)
  CHANGELOG.md
  src/editors/Flow/view/Components/FlowBottomBar/FlowBottomBar.jsx
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Components/interface/MainInterface.js
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/BaseFlow.jsx
Labels: revert

#174 FP-2542: Removed code that prevented flow validations from running
  CHANGELOG.md
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/BaseFlow.jsx
Labels: bug, enhancement
