Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-01, with the labels that each got.

#71 FP-2181: Removed function call that was triggering the issue
  src/editors/Flow/view/Utils/utils.js
  src/editors/Node/view/Node.jsx
  src/plugins/DocManager/DocManager.js
  src/stories/_mockLogin.js
Labels: bug, refactor

#72 new release
  src/editors/Flow/view/Utils/utils.js
  src/editors/Node/view/Node.jsx
  src/plugins/DocManager/DocManager.js
  src/stories/_mockLogin.js
Labels: release candidate

#74 new release
  package-lock.json
  package.json
  src/plugins/Dialog/components/AppDialog/AppDialog.jsx
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/stories/AppCE.jsx
  src/stories/components/Logs/Logs.jsx
  src/stories/components/Logs/Logs.stories.jsx
Labels: bug, release candidate

#75 update libs
  package-lock.json
  package.json
Labels: release candidate

#76 dummy
  CHANGELOG.md
Labels: release candidate
