Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-06, with the labels that each got.

#138 New release
  CHANGELOG.md
  index.js
  src/App/BaseApp.js
  src/decorators/withAlerts.jsx
  src/decorators/withKeyBinds.jsx
  src/editors/Callback/view/Callback.jsx
  src/editors/Callback/view/Menu.jsx
  src/editors/Callback/view/dialogs/AddImport.jsx
  src/editors/Callback/view/dialogs/EditMessage.jsx
  src/editors/Configuration/view/styles.js
  src/editors/Flow/view/Components/Explorer/styles.js
  src/editors/Flow/view/Components/FlowBottomBar/styles.js
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Components/Menus/ContainerMenu.jsx
  src/editors/Flow/view/Components/Menus/Menu.jsx
  src/editors/Flow/view/Components/Menus/NodeMenu.jsx
  src/editors/Flow/view/Components/Warnings/styles.js
  src/editors/Flow/view/Components/interface/MainInterface.js
  src/editors/Flow/view/Components/interface/canvas.js
  src/editors/Flow/view/Core/Graph/GraphValidator.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/BaseFlow.jsx
  src/editors/Flow/view/Views/hooks/useMainInterface.jsx
  src/editors/Flow/view/Views/styles.js
  src/editors/Node/view/Node.jsx
  src/editors/Node/view/components/IOConfig/IOConfig.jsx
  src/editors/Node/view/components/IOConfig/IOPorts/components/styles.js
  src/editors/_shared/HtmlTooltip/HtmlTooltip.jsx
  src/editors/_shared/KeyValueTable/KeyValueEditorDialog.jsx
  src/editors/_shared/MaterialTable/MaterialTable.jsx
  src/editors/_shared/hooks/DataTypes/AbstractDataType.js
  src/plugins/Alerts/Alerts.js
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/AlertDialog/AlertBeforeAction.jsx
  src/plugins/Dialog/components/AlertDialog/AlertDialog.jsx
  src/plugins/Dialog/components/AlertDialog/styles.js
  src/plugins/Dialog/components/AppDialog/AppDialog.jsx
  src/plugins/Dialog/components/ConfirmationDialog/ConfirmationDialog.jsx
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/plugins/Dialog/components/FormDialog/NewDocumentDialog.jsx
  src/plugins/Dialog/components/FormDialog/hooks/useNewDocument.js
  src/plugins/Dialog/components/FormDialog/styles.js
  src/plugins/DocManager/DocManager.js
  src/plugins/hosts/SidePanel/SidePanel.jsx
  src/plugins/views/Explorer/Explorer.jsx
  src/plugins/views/MainMenu/MainMenu.jsx
  src/plugins/views/SystemBar/builder/buildMenus.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/stories/components/PluginManager/PluginManager.stories.jsx
  src/themes.js
  src/tools/HomeTab/components/QuickAccess.jsx
  src/utils/Constants.js
  src/utils/Utils.js
  src/utils/form.js
  src/utils/generalFunctions.js
  src/utils/noremix.js
  src/utils/shortcuts.js
Labels: bug, release candidate

#147 FP-2447 - Info tab closes when adding an import
  .eslintrc.js
  package-lock.json
  package.json
  scripts/eslint.sh
  src/engine/ReactPlugin/ToolReactPlugin.js
Labels: bug

#154 Revert "New release (#133)"
  src/models/subModels/Parameter/Parameter.js
Labels: revert

#153 New release
  .eslintrc.js
  CHANGELOG.md
  index.js
  package-lock.json
  package.json
  scripts/eslint.sh
  src/App/BaseApp.js
  src/decorators/withKeyBinds.jsx
  src/editors/Callback/view/Menu.jsx
  src/editors/Flow/view/Components/Menus/Menu.jsx
  src/editors/Flow/view/Components/Menus/sub-components/RowKeyValue.jsx
  src/editors/Flow/view/Components/Nodes/BaseNode/BasePort.js
  src/editors/Flow/view/Components/Warnings/styles.js
  src/editors/Flow/view/Components/interface/MainInterface.js
  src/editors/Flow/view/Components/interface/canvas.js
  src/editors/Flow/view/Core/Graph/GraphBase.js
  src/editors/Flow/view/Core/Graph/GraphValidator.js
  src/editors/Flow/view/Flow.jsx
  src/editors/Flow/view/Views/Monitoring.jsx
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/engine/ReactPlugin/ViewReactPlugin.js
  src/plugins/views/Explorer/components/ListItemTree/ItemRow.jsx
  src/plugins/views/MainMenu/MainMenu.jsx
  src/plugins/views/SystemBar/builder/buildMenus.js
  src/stories/AppCE.stories.jsx
  src/stories/_mockLogin.js
  src/stories/components/Bookmarks/Bookmarks.stories.jsx
  src/stories/components/ConfigurationSelector.stories.jsx
  src/stories/components/Logs/Logs.stories.jsx
  src/tools/HomeTab/components/QuickAccess.jsx
  src/utils/Utils.js
  src/utils/generalFunctions.js
  src/utils/shortcuts.js
Labels: bug, release candidate

#155 FP-2467: We are now correctly deleting exposed ports on node deletion
  CHANGELOG.md
  src/editors/Flow/model/Flow.js
  src/editors/Flow/model/subModels/ExposedPorts/ExposedPortsManager.js
Labels: bug
