Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2023-09, with the labels that each got.

#220 FP-2585: Added optional chaining to prevent crash
  src/editors/Flow/model/Flow.js
Labels: bug

#221 FP-2477: Added validation to not close drawer
  CHANGELOG.md
  src/decorators/withBookmarks.jsx
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
Labels: bug, enhancement

#215 FP-2589: Removed references to tty-pt/styles package
  package-lock.json
  package.json
  src/stories/AppCE.jsx
Labels: dependencies, refactor

#222 FP-2560: Set default for validation Name to empty to prevent error
  CHANGELOG.md
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/utils/Utils.js
Labels: bug

#217 FP-2581: Fix useCallback issue preventing start/stop nodes on tree view
  CHANGELOG.md
  src/editors/Flow/view/Flow.jsx
Labels: bug

#224 Update lib-ide Version to 1.0.0-59
  package-lock.json
  package.json
Labels: enhancement

#225 Release 1.0.0-59
  CHANGELOG.md
  package-lock.json
  package.json
  src/decorators/withBookmarks.jsx
  src/editors/Flow/model/Flow.js
  src/editors/Flow/view/Flow.jsx
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/models/Model/BaseModel.js
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/plugins/DocManager/DocManager.js
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/store/Store.js
  src/stories/AppCE.jsx
  src/utils/Utils.js
Labels: enhancement, release candidate, dependencies

#229 Bumped to version 69
  package-lock.json
  package.json
Labels: enhancement

#231 Bumped version to 69
  package-lock.json
  package.json
Labels: enhancement

#233 Release 1.0.0-70
  .storybook/main.js
  .storybook/preview.js
  index.js
  package-lock.json
  package.json
  src/decorators/index.js
  src/decorators/withTheme.jsx
  src/editors/Callback/view/dialogs/AddImport.jsx
  src/editors/Callback/view/dialogs/EditMessage.jsx
  src/editors/Flow/view/Components/Debugging/styles.js
  src/editors/Flow/view/Components/FlowBottomBar/FlowBottomBar.jsx
  src/editors/Flow/view/Components/Tooltips/FlowTooltip.jsx
  src/editors/Flow/view/Components/Warnings/Warnings.jsx
  src/editors/Flow/view/Components/Warnings/styles.js
  src/editors/Flow/view/styles.js
  src/editors/Node/view/components/IOConfig/IOConfig.jsx
  src/editors/_shared/KeyValueTable/KeyValueEditorDialog.jsx
  src/editors/_shared/KeyValueTable/ParametersEditorDialog.jsx
  src/plugins/Dialog/Dialog.js
  src/plugins/Dialog/components/AppDialog/AppDialog.jsx
  src/plugins/Dialog/components/FormDialog/FormDialog.jsx
  src/plugins/hosts/DrawerPanel/styles.js
  src/stories/AppCE.jsx
  src/themes.js
Labels: bug, release candidate, dependencies

#235 FP-2477: No longer closing drawer on tab change
  src/decorators/withBookmarks.jsx
  src/plugins/views/Tabs/hooks/useTabLayout.js
Labels: bug
