Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2024-11, with the labels that each got.

#368 FP-2976: Remove unused slash when scope is not passed
  src/App/BaseApp.js
  src/utils/keybinds.js
Labels: bug

#370 FP-3012: Menus were resetting on every editor click. Fixed this
  CHANGELOG.md
  index.js
  package.json
  pnpm-lock.yaml
  src/App/BaseApp.js
  src/decorators/index.js
  src/decorators/withBookmarks.jsx
  src/decorators/withMenuHandler.jsx
  src/editors/Callback/view/Callback.jsx
  src/editors/Configuration/view/Configuration.jsx
  src/editors/Flow/view/Flow.jsx
  src/editors/Node/view/Node.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/plugins/DocManager/Examples/README.md
  src/plugins/Orchestrator/Orchestrator.ts
  src/plugins/views/Tabs/Tabs.jsx
  src/plugins/views/Tabs/hooks/useTabLayout.js
  src/utils/Constants.js
  src/utils/Utils.js
  src/utils/keybinds.js
Labels: bug, enhancement, refactor

#373 Release 1.4.2
  CHANGELOG.md
  package.json
Labels: release candidate

#379 FP-3068: FP-3069: Removed scope from Drawers. Voided keybinds on inputs
  CHANGELOG.md
  src/editors/Flow/view/Components/Explorer/Explorer.jsx
  src/editors/Flow/view/Flow.jsx
  src/engine/ReactPlugin/EditorReactPlugin.js
  src/engine/ReactPlugin/ToolReactPlugin.js
  src/plugins/Orchestrator/Orchestrator.ts
  src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
  src/plugins/views/Explorer/Explorer.jsx
  src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
  src/utils/Constants.js
  src/utils/components/Search/Search.jsx
  src/utils/keybinds.js
Labels: bug, enhancement
