Repository MOV-AI/frontend-npm-lib-ide, pull requests merged in 2025-07, with the labels that each got.

#408 FP-3081: Handling port modal state manually
  CHANGELOG.md
  src/editors/Flow/view/Components/Nodes/BaseNode/BasePort.js
  src/editors/Flow/view/Components/Tooltips/PortTooltip.jsx
  src/editors/Flow/view/Constants/constants.js
  src/editors/Flow/view/Flow.jsx
Labels: bug, enhancement

#409 FP-2905: When changing a node template, the node is not updated in the flow
  CHANGELOG.md
  src/editors/Flow/view/Views/BaseFlow.jsx
Labels: bug

#411 FP-3163: Clicking on the flow of a member opens the flow with the master
  CHANGELOG.md
  src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
  src/editors/Flow/view/Flow.jsx
  src/utils/Constants.js
Labels: bug

#413 FP-3262: Added robot version to Workspace baseKey
  CHANGELOG.md
  src/utils/Workspace.js
Labels: enhancement

#410 FP-3254: Added instructions to the ROS_VALID_NAMES const errors
  CHANGELOG.md
  src/editors/Flow/view/Core/Graph/GraphValidator.js
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/utils/Constants.js
Labels: bug, enhancement

#419 - Minor fix in using own web socket for the FlowDB and NodeDB
  CHANGELOG.md
  package.json
  src/editors/Flow/store/FlowDB.js
  src/editors/Flow/store/FlowStore.test.js
  src/editors/Node/store/NodeDB.js
Labels: enhancement
